### ISSUE TITLE
Verify signed message

### ISSUE THREAD

**Issue by dmytronasyrov** [ElrondNetwork/elrond-sdk-erdjava#15]
I need to make a backend verification of the nonce signed on a frontend. I don't see any message verification functionality in tests or classes. Please point me to the code I can use to verify the signed nonce string.

**Comment by bogdan-rosianu** [comment]
Hello! Right now we don't have support for signed message. We'll add it. Until then, maybe the erdjs implementation can provide some guidance: 
https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/signableMessage.ts

**Comment by bogdan-rosianu** [comment]
Update: pending work on #16

**Comment by bogdan-rosianu** [comment]
The new version is released and available on maven:
- https://central.sonatype.dev/artifact/com.elrond/erdjava/1.0.4
